Add trivy
logzio/logzio-agent-manifest pull request #76
Opened 2023-03-01 10:49 UTC by ShiranAvidov

2023-03-02 12:02 UTC, mirii1994 requested changes
Great work, see my suggestions.
Regarding agent version - since we're adding a new capability, maybe we should bump it to 1.1.0 instead of 1.0.44.

2023-03-02 12:02 UTC, mirii1994 commented on configs/k8s-aks.json
> +                  "hint": "Check this box if you want Logz.io Telemetry Collector to collect security risks in your cluster.",
```suggestion
                  "hint": "Check this box if you want Logz.io Telemetry Collector to scan and inform about security risks in your cluster."
```

2023-03-09 15:45 UTC, Doron-Bargo approved these changes

2023-03-09 15:48 UTC, Doron-Bargo commented
I agree with Miri comment on the version. We should advance to 1.1

2023-04-17 16:41 UTC, merged